# Generated by Django 4.2.6 on 2023-12-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakeid", models.CharField(max_length=250)),
                ("cakename", models.CharField(max_length=250)),
                ("userid", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=250)),
                ("booking", models.CharField(max_length=250)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("Status", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="caketable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakename", models.CharField(max_length=250)),
                ("cakeprice", models.CharField(max_length=250)),
                ("cakecategory", models.CharField(max_length=250)),
                ("brand", models.CharField(max_length=250)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakeid", models.CharField(max_length=200)),
                ("userid", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("cakeprice", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("cakecategory", models.CharField(max_length=200)),
                ("cartstatus", models.CharField(max_length=200)),
                ("totalprice", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("cakename", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakeid", models.CharField(max_length=200)),
                ("userid", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("order_status", models.CharField(max_length=200)),
                ("totalprice", models.CharField(max_length=200)),
                ("cakename", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productid", models.CharField(max_length=250)),
                ("cakename", models.CharField(max_length=250)),
                ("userid", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=250)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("comment", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakeid", models.CharField(max_length=200)),
                ("userid", models.CharField(max_length=200)),
                ("cakename", models.CharField(max_length=200)),
                ("cakeprice", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("cakecategory", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250)),
                ("Phoneno", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("adress", models.CharField(blank=True, max_length=300, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "Loginid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creamyhubapp.login",
                    ),
                ),
            ],
        ),
    ]
