# Generated by Django 4.2.6 on 2023-10-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakeid", models.CharField(max_length=250)),
                ("cakename", models.CharField(max_length=250)),
                ("userid", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=250)),
                ("booking", models.CharField(max_length=250)),
                (
                    "image",
                    models.ImageField(null=True, upload_to="", verbose_name="images/"),
                ),
                ("Status", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="caketable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakename", models.CharField(max_length=250)),
                ("cakeprice", models.CharField(max_length=250)),
                ("cakecategory", models.CharField(max_length=250)),
                ("brand", models.CharField(max_length=250)),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productid", models.CharField(max_length=250)),
                ("cakename", models.CharField(max_length=250)),
                ("userid", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=250)),
                ("image", models.ImageField(null=True, upload_to="", verbose_name="")),
                ("comment", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250)),
                ("Phoneno", models.CharField(max_length=250)),
                ("Email", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                (
                    "Loginid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creamyhubapp.login",
                    ),
                ),
            ],
        ),
    ]
