# Generated by Django 4.2.6 on 2023-10-29 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="Email",
            new_name="email",
        ),
    ]
