# Generated by Django 4.2.6 on 2023-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="datetime",
            new_name="datetime_note",
        ),
        migrations.AddField(
            model_name="payment",
            name="userid",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
