# Generated by Django 4.2.6 on 2023-12-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cakecategory",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="cakeprice",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="orderstatus",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="username",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
