# Generated by Django 4.2.6 on 2023-10-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0002_rename_email_registration_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="role",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
