# Generated by Django 4.2.6 on 2023-12-11 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "creamyhubapp",
            "0002_order_cakecategory_order_cakeprice_order_orderstatus_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="userid",
            new_name="user",
        ),
    ]
