# Generated by Django 4.2.6 on 2023-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0003_login_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="adress",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
