# Generated by Django 4.2.6 on 2023-12-11 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0003_rename_userid_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="userid",
        ),
    ]
