# Generated by Django 4.2.6 on 2023-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0004_registration_adress_registration_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
