# Generated by Django 4.2.6 on 2023-11-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0005_alter_booking_image_alter_review_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caketable",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
