# Generated by Django 4.2.6 on 2023-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0006_alter_caketable_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caketable",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="../../assets/"),
        ),
    ]
