# Generated by Django 4.2.6 on 2023-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0008_alter_caketable_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="Name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
