# Generated by Django 4.2.6 on 2023-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0010_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="username",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
