# Generated by Django 4.2.6 on 2023-11-04 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0011_wishlist_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="Name",
        ),
    ]
