# Generated by Django 4.2.6 on 2023-11-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0012_remove_login_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cakeid", models.CharField(max_length=200)),
                ("userid", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("cakeprice", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("cakecategory", models.CharField(max_length=200)),
                ("cartstatus", models.CharField(max_length=200)),
                ("totalprice", models.CharField(max_length=200)),
            ],
        ),
    ]
