# Generated by Django 4.2.6 on 2023-11-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0013_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="Name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
