# Generated by Django 4.2.6 on 2023-11-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creamyhubapp', '0014_login_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Name',
        ),
    ]
