# Generated by Django 4.2.6 on 2023-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0015_remove_login_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="username",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
