# Generated by Django 4.2.6 on 2023-11-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0016_cart_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cakename",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
