# Generated by Django 4.2.6 on 2023-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0017_cart_cakename"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200)),
                ("cakeid", models.CharField(max_length=200)),
                ("cakename", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("cakeprice", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("order_status", models.CharField(max_length=200)),
            ],
        ),
    ]
