# Generated by Django 4.2.6 on 2023-11-16 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0018_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="brand",
        ),
    ]
