# Generated by Django 4.2.6 on 2023-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0020_rename_cakeid_order_adress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="Phoneno",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
