# Generated by Django 4.2.6 on 2023-12-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0021_order_name_order_phoneno_order_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caketable",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
    ]
