# Generated by Django 4.2.6 on 2023-12-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creamyhubapp", "0022_alter_caketable_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caketable",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
